/**
 * @credits
 *
 *  - The data of fictitious employees was
 *  generated with the application of
 *  FakePersonGenerator.com
 */
export const mockedEmployees = [
  {
    firstName: "Alice",
    lastName: "Lamb",
    dateOfBirth: "01/09/1970",
    department: "Legal",
    startDate: "01/09/1989",
    street: "2619 Jenna Lane",
    city: "Cincinnati",
    state: "OH",
    zipCode: "45236",
  },
  {
    firstName: "Suzanne",
    lastName: "Rios",
    dateOfBirth: "02/07/1992",
    department: "Human Ressources",
    startDate: "30/11/2008",
    street: "4993 Irving Place",
    city: "Olivette",
    state: "MO",
    zipCode: "63132",
  },
  {
    firstName: "Anita",
    lastName: "Rios",
    dateOfBirth: "03/17/1999",
    department: "Engineering",
    startDate: "20/05/2019",
    street: "4155 Dovetail Drive",
    city: "Arlington Heights",
    state: "IL",
    zipCode: "60004",
  },
  {
    firstName: "Rafael",
    lastName: "Applebaum",
    dateOfBirth: "05/04/1993",
    department: "Sales",
    startDate: "06/11/2010",
    street: "3219 Single Street",
    city: "Waltham",
    state: "MA",
    zipCode: "02154",
  },
  {
    firstName: "Hazel",
    lastName: "Kraus",
    dateOfBirth: "08/05/1990",
    department: "Marketing",
    startDate: "03/28/2002",
    street: "776 Ward Road",
    city: "Ossining",
    state: "NY",
    zipCode: "10562",
  },
  {
    firstName: "Alice",
    lastName: "Lamb",
    dateOfBirth: "01/09/1970",
    department: "Legal",
    startDate: "01/09/1989",
    street: "2619 Jenna Lane",
    city: "Cincinnati",
    state: "OH",
    zipCode: "45236",
  },
  {
    firstName: "Suzanne",
    lastName: "Rios",
    dateOfBirth: "02/07/1992",
    department: "Human Ressources",
    startDate: "30/11/2008",
    street: "4993 Irving Place",
    city: "Olivette",
    state: "MO",
    zipCode: "63132",
  },
  {
    firstName: "Anita",
    lastName: "Rios",
    dateOfBirth: "03/17/1999",
    department: "Engineering",
    startDate: "20/05/2019",
    street: "4155 Dovetail Drive",
    city: "Arlington Heights",
    state: "IL",
    zipCode: "60004",
  },
  {
    firstName: "Rafael",
    lastName: "Applebaum",
    dateOfBirth: "05/04/1993",
    department: "Sales",
    startDate: "06/11/2010",
    street: "3219 Single Street",
    city: "Waltham",
    state: "MA",
    zipCode: "02154",
  },
  {
    firstName: "Hazel",
    lastName: "Kraus",
    dateOfBirth: "08/05/1990",
    department: "Marketing",
    startDate: "03/28/2002",
    street: "776 Ward Road",
    city: "Ossining",
    state: "NY",
    zipCode: "10562",
  },
  {
    firstName: "Alice",
    lastName: "Lamb",
    dateOfBirth: "01/09/1970",
    department: "Legal",
    startDate: "01/09/1989",
    street: "2619 Jenna Lane",
    city: "Cincinnati",
    state: "OH",
    zipCode: "45236",
  },
  {
    firstName: "Suzanne",
    lastName: "Rios",
    dateOfBirth: "02/07/1992",
    department: "Human Ressources",
    startDate: "30/11/2008",
    street: "4993 Irving Place",
    city: "Olivette",
    state: "MO",
    zipCode: "63132",
  },
  {
    firstName: "Anita",
    lastName: "Rios",
    dateOfBirth: "03/17/1999",
    department: "Engineering",
    startDate: "20/05/2019",
    street: "4155 Dovetail Drive",
    city: "Arlington Heights",
    state: "IL",
    zipCode: "60004",
  },
  {
    firstName: "Rafael",
    lastName: "Applebaum",
    dateOfBirth: "05/04/1993",
    department: "Sales",
    startDate: "06/11/2010",
    street: "3219 Single Street",
    city: "Waltham",
    state: "MA",
    zipCode: "02154",
  },
  {
    firstName: "Hazel",
    lastName: "Kraus",
    dateOfBirth: "08/05/1990",
    department: "Marketing",
    startDate: "03/28/2002",
    street: "776 Ward Road",
    city: "Ossining",
    state: "NY",
    zipCode: "10562",
  },
]
